pipeline:
  build:
    image: golang:1.10.3
    pull: true
    commands:
      - make build
      - make test

  # publish:
  #   commands:
  #     - echo $FOO
  #   when:
  #     event: deployment
  #     environment: init

workspace:
  base: /go
  path: src/github.com/glower/hello-web
